import { IAbility } from "../interfaces/ability.ts";
import { IAncientTrait } from "./ancientTrait.ts";
import { IAttack } from "../interfaces/attack.ts";
import { IResistance } from "../interfaces/resistance.ts";
import { IWeakness } from "../interfaces/weakness.ts";
import { ICardImage } from "./image.ts";
import { ICardmarket } from "./cardmarket.ts";
import { ILegality } from "./legality.ts";
import { ISet } from "./set.ts";
import { ITCGPlayer } from "./tcgplayer.ts";

export interface ICard {
  id: string;
  name: string;
  supertype: string;
  subtypes: string[];
  hp?: string;
  types?: string[];
  evolvesFrom?: string;
  evolvesTo?: string[];
  rules?: string[];
  ancientTrait?: IAncientTrait;
  abilities?: IAbility[];
  attacks?: IAttack[];
  weaknesses?: IWeakness[];
  resistances?: IResistance[];
  retreatCost?: string[];
  convertedRetreatCost?: number;
  set?: ISet;
  number: string;
  artist?: string;
  rarity: string;
  flavorText?: string;
  nationalPokedexNumbers?: number[];
  legalities?: ILegality;
  regulationMark?: string;
  images: ICardImage;
  tcgplayer?: ITCGPlayer;
  cardmarket?: ICardmarket;
}
